// Cup Dashboard — approved premium racing workspace standard.
(function(){
  function dRows(){return (cupData?.horses||[]).map(h=>{const p=typeof projectedRec==='function'?projectedRec(h.horse):null;const r=typeof publicFormRating==='function'?publicFormRating(h.horse):null;const runs=typeof publicRatedRuns==='function'?publicRatedRuns(h.horse):[];const lens=typeof cupPublicLens==='function'?cupPublicLens(h.horse):null;const ras=typeof publicRasPeak==='function'?publicRasPeak(h.horse):null;const m=typeof marketUniverse==='function'?marketUniverse().find(x=>x.horse===h.horse):null;const o=typeof orderOfficialWeight==='function'?orderOfficialWeight(h.horse):null;const w=typeof weightRec==='function'?weightRec(h.horse):null;const kg=Number.isFinite(o)?o:(w&&Number.isFinite(Number(w.predictedKg))?Number(w.predictedKg):null);return {h,p,r,runs,lens,ras,m,kg,latest:runs[0]||null};});}
  function market(x){if(!x.m)return '—';return `$${Number(x.m.last.odds).toFixed(2)}`;}
  function trajectory(x){if(!x.r||x.r.trajectory==null)return '—';const n=Number(x.r.trajectory),cls=n>=4?'green':n<=-4?'red':'gold';return `<span class="dash-trend ${cls}">${n>0?'+':''}${n.toFixed(1)}</span>`;}
  function changes(){if(typeof commandChangeFeed!=='function')return [];return commandChangeFeed().slice(0,6);}
  function dashTable(rows){return `<div class="panel dash-board"><div class="dash-board-head"><div><h3>Cup Contender Board</h3><span>All 101 nominees · live form, handicap and market view</span></div><span>${rows.length} horses</span></div><div class="table-wrap"><table class="data-table dash-table"><thead><tr><th>#</th><th>Horse</th><th>Country</th><th>Projected</th><th>PFR</th><th>Peak</th><th>2800m+</th><th>Trajectory</th><th>Last Start</th><th>Wt</th><th>Market</th><th>Cup Lens</th></tr></thead><tbody>${rows.map((x,i)=>`<tr><td>${i+1}</td><td class="horse">${horseLink(x.h.horse)}</td><td>${x.h.country||'—'}</td><td>${x.p?'#'+x.p.rank:'—'}</td><td><strong>${x.r?x.r.current.toFixed(1):'—'}</strong></td><td>${x.r?x.r.peak.toFixed(1):'—'}</td><td>${x.r?.longStayPeak!=null?x.r.longStayPeak.toFixed(1):'—'}</td><td>${trajectory(x)}</td><td class="wrap-cell">${x.latest?`${x.latest.finish||'—'} · ${x.latest.race||'—'}`:'—'}</td><td>${x.kg!=null?x.kg.toFixed(1):'—'}</td><td class="dash-market">${market(x)}</td><td><strong>${x.lens?x.lens.score.toFixed(1):'—'}</strong></td></tr>`).join('')}</tbody></table></div></div>`;}
  dashboard=function(){const rows=dRows();const projected=rows.filter(x=>x.p).sort((a,b)=>a.p.rank-b.p.rank);const pfr=[...rows].filter(x=>x.r).sort((a,b)=>b.r.current-a.r.current)[0];const stay=[...rows].filter(x=>x.r?.longStayPeak!=null).sort((a,b)=>b.r.longStayPeak-a.r.longStayPeak)[0];const lens=[...rows].filter(x=>x.lens).sort((a,b)=>b.lens.score-a.lens.score)[0];const marketRows=rows.filter(x=>x.m).sort((a,b)=>Number(a.m.last.odds)-Number(b.m.last.odds));const fav=marketRows[0];const updates=changes();return `<div class="dash-head"><div><div class="kicker">FLEMINGTON · 3200M · GROUP 1</div><h2>Cup Dashboard</h2></div></div><section class="dash-metrics"><div><span>NOMINEES</span><strong>101</strong><small>Melbourne Cup universe</small></div><div><span>PROJECTED FIELD</span><strong>${projected.length}/24</strong><small>${projected[0]?.h.horse||'—'} leads projection</small></div><div><span>TOP PFR</span><strong>${pfr?pfr.r.current.toFixed(1):'—'}</strong><small>${pfr?.h.horse||'—'}</small></div><div><span>2800M+ PEAK</span><strong>${stay?stay.r.longStayPeak.toFixed(1):'—'}</strong><small>${stay?.h.horse||'—'}</small></div><div><span>MARKET LEADER</span><strong>${fav?market(fav):'—'}</strong><small>${fav?.h.horse||'—'}</small></div><div><span>CUP LENS</span><strong>${lens?lens.lens.score.toFixed(1):'—'}</strong><small>${lens?.h.horse||'—'}</small></div></section><section class="panel dash-updates"><div class="dash-board-head"><div><h3>Latest Key Updates</h3><span>Most recent material Cup activity</span></div></div><div class="dash-update-grid">${updates.map(x=>`<button onclick="${x.horse&&horseByName(x.horse)?`openHorse('${x.horse.replace(/'/g,"\\'")}')`:`openView('${x.view||'dashboard'}')`}"><span>${x.type||'UPDATE'}</span><strong>${x.horse||'Cup'} · ${x.title||''}</strong><small>${x.detail||''}</small></button>`).join('')}</div></section>${dashTable(rows.sort((a,b)=>(a.p?.rank??999)-(b.p?.rank??999)||(b.lens?.score??-1)-(a.lens?.score??-1)||a.h.horse.localeCompare(b.h.horse)))}`;};
})();
