// International Raiders — approved compact racing workspace standard.
(function(){
 let irFilter='all',irQuery='',irSort='pfr';
 const num=v=>(v!==null&&v!==undefined&&v!==''&&Number.isFinite(Number(v)))?Number(v):null;
 const code=h=>({AU:'AUS',AUS:'AUS',NZ:'NZ',IE:'IRE',IRE:'IRE',UK:'GB',GB:'GB',FR:'FR',JP:'JPN',JPN:'JPN',US:'USA',USA:'USA',DE:'GER',GER:'GER'}[String(h?.country||'').toUpperCase()]||String(h?.country||'—').toUpperCase());
 function horses(){return (cupData?.horses||[]).filter(h=>h.trainingRegion==='International')}
 function rating(n){try{return typeof publicFormRating==='function'?publicFormRating(n):null}catch(_){return null}}
 function runs(n){try{return typeof publicRatedRuns==='function'?publicRatedRuns(n):[]}catch(_){return []}}
 function projected(n){return (projectedFieldData?.projected24||[]).find(x=>x.horse===n)||null}
 function market(n){try{const r=typeof marketUniverse==='function'?marketUniverse().find(x=>x.horse===n):null,o=num(r?.last?.odds);return o&&o>1?o:null}catch(_){return null}}
 function weight(n){try{const o=typeof orderOfficialWeight==='function'?orderOfficialWeight(n):null;if(num(o)!=null)return num(o);const w=typeof weightRec==='function'?weightRec(n):null;return num(w?.predictedKg)}catch(_){return null}}
 function base(n){try{const v=typeof currentBase==='function'?currentBase(n):null;return !v||v==='Researching'?'—':String(v).replace(/HORSE-SPECIFIC CURRENT/gi,'').replace(/TRAINER BASE FALLBACK/gi,'').trim()}catch(_){return '—'}}
 function last(n){const r=runs(n)[0];if(r)return r;const e=[...(leadupData?.events||[])].filter(x=>x.horse===n&&x.type==='Result').sort((a,b)=>String(b.date||'').localeCompare(String(a.date||'')))[0];return e?{date:e.date,race:e.race,track:e.track,distanceM:e.distanceM,finish:e.result,going:e.going}:null}
 function prep(n){try{return typeof prepRecord==='function'?prepRecord(n):null}catch(_){return null}}
 function qualified(n){try{return !!(qualificationData?.qualified||[]).find(x=>x.horse===n)}catch(_){return false}}
 function campaign(n){const p=prep(n);if(p)return p.campaignStatus||'Cup campaign';const e=[...(leadupData?.events||[])].filter(x=>x.horse===n).sort((a,b)=>String(b.date||'').localeCompare(String(a.date||'')))[0];if(e?.status==='Golden Ticket')return 'Qualified';if(e?.type==='Result')return 'Campaign active';return 'Nominated'}
 function rows(){let a=horses().map(h=>({h,r:rating(h.horse),p:projected(h.horse),m:market(h.horse),w:weight(h.horse),l:last(h.horse)}));if(irFilter==='projected')a=a.filter(x=>x.p);else if(irFilter==='rated')a=a.filter(x=>x.r);else if(irFilter==='stayers')a=a.filter(x=>x.r?.longStayPeak!=null);else if(irFilter==='campaign')a=a.filter(x=>prep(x.h.horse)||(leadupData?.events||[]).some(e=>e.horse===x.h.horse));else if(irFilter==='qualified')a=a.filter(x=>qualified(x.h.horse));if(irQuery)a=a.filter(x=>`${x.h.horse} ${x.h.trainer} ${code(x.h)} ${base(x.h.horse)} ${campaign(x.h.horse)}`.toLowerCase().includes(irQuery.toLowerCase()));const sorters={pfr:(a,b)=>(num(b.r?.current)??-999)-(num(a.r?.current)??-999),market:(a,b)=>(a.m??9999)-(b.m??9999),order:(a,b)=>(a.p?.rank??999)-(b.p?.rank??999),az:(a,b)=>a.h.horse.localeCompare(b.h.horse)};return a.sort(sorters[irSort]||sorters.pfr)}
 function summary(){const a=horses();return {n:a.length,rated:a.filter(h=>rating(h.horse)).length,stayers:a.filter(h=>rating(h.horse)?.longStayPeak!=null).length,projected:a.filter(h=>projected(h.horse)).length,campaign:a.filter(h=>prep(h.horse)||(leadupData?.events||[]).some(e=>e.horse===h.horse)).length}}
 function view(){const s=summary();return `<div class="ir-head"><div><div class="kicker">FLEMINGTON · 3200M · GROUP 1</div><h2>International Raiders</h2><p>Complete performance, handicap and campaign view of the 23 overseas-trained nominees.</p></div></div><section class="ir-summary"><div><span>INTERNATIONAL</span><strong>${s.n}</strong><small>Overseas-trained nominees</small></div><div><span>PFR LOADED</span><strong>${s.rated}</strong><small>Current form rating available</small></div><div><span>2800M+ EVIDENCE</span><strong>${s.stayers}</strong><small>Long-staying rating loaded</small></div><div><span>PROJECTED 24</span><strong>${s.projected}</strong><small>Current field projection</small></div><div><span>CAMPAIGN FORM</span><strong>${s.campaign}</strong><small>Dated run or campaign update</small></div></section><div class="ir-toolbar"><div class="filters"><button class="filter active" data-ir="all">All Raiders <span>${s.n}</span></button><button class="filter" data-ir="projected">Projected 24 <span>${s.projected}</span></button><button class="filter" data-ir="rated">PFR Loaded <span>${s.rated}</span></button><button class="filter" data-ir="stayers">2800m+ <span>${s.stayers}</span></button><button class="filter" data-ir="campaign">Campaign Form <span>${s.campaign}</span></button><button class="filter" data-ir="qualified">Qualified</button></div><input id="ir-search" class="search" placeholder="Search horse, trainer or base…"><select id="ir-sort"><option value="pfr">Sort: Current PFR</option><option value="order">Sort: Projected Order</option><option value="market">Sort: Market</option><option value="az">Sort A–Z</option></select></div><div class="panel ir-board"><div class="ir-boardhead"><div><h3>International Raiders Board</h3><p>Performance and campaign information only — no backend research labels.</p></div><span id="ir-count">${s.n} horses</span></div><div class="table-wrap"><table class="data-table ir-table"><thead><tr><th>#</th><th>Horse</th><th>Country</th><th>Trainer</th><th>Training Base</th><th>Current PFR</th><th>2800m+</th><th>Last Start</th><th>Result</th><th>Wt</th><th>Market</th><th>Projected</th><th>Campaign</th></tr></thead><tbody id="ir-body"></tbody></table></div></div>`}
 function paint(){const a=rows(),b=document.getElementById('ir-body');if(!b)return;b.innerHTML=a.map((x,i)=>`<tr onclick="openHorse('${x.h.horse.replace(/'/g,"\\'")}')"><td>${i+1}</td><td class="horse">${typeof silkHorse==='function'?silkHorse(x.h.horse):horseLink(x.h.horse)}</td><td>${code(x.h)}</td><td>${x.h.trainer||'—'}</td><td class="ir-base">${base(x.h.horse)}</td><td class="ir-pfr">${num(x.r?.current)!=null?num(x.r.current).toFixed(1):'—'}</td><td>${num(x.r?.longStayPeak)!=null?num(x.r.longStayPeak).toFixed(1):'—'}</td><td class="ir-last">${x.l?`${x.l.date||'—'} · ${x.l.race||x.l.track||'—'}`:'—'}</td><td><strong>${x.l?.finish||x.l?.result||'—'}</strong></td><td>${x.w!=null?x.w.toFixed(1):'—'}</td><td class="ir-market">${x.m?`$${x.m.toFixed(2)}`:'—'}</td><td>${x.p?`#${x.p.rank}`:'—'}</td><td><span class="ir-campaign ${qualified(x.h.horse)?'qualified':''}">${campaign(x.h.horse)}</span></td></tr>`).join('');document.getElementById('ir-count').textContent=`Showing ${a.length} of 23 horses`}
 function show(){currentView='international';selectedHorse=null;document.querySelectorAll('#nav button[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view==='international'));document.getElementById('page-title').textContent='International Raiders';const root=document.getElementById('app-content');const draw=()=>{root.innerHTML=view();paint()};const waits=[];if(typeof formIntelData!=='undefined'&&!formIntelData&&typeof loadFormIntel==='function')waits.push(loadFormIntel());if(!leadupData&&typeof loadLeadups==='function')waits.push(loadLeadups());if(!projectedFieldData&&typeof loadProjectedField==='function')waits.push(loadProjectedField());if(!weightPredictions&&typeof loadExtras==='function')waits.push(loadExtras());if(!internationalPrepData&&typeof loadInternationalPrep==='function')waits.push(loadInternationalPrep());if(typeof marketWorkbenchPromise!=='undefined'&&!marketWorkbenchPromise&&typeof loadMarketWorkbench==='function')waits.push(loadMarketWorkbench());if(waits.length){root.innerHTML='<div class="placeholder">Loading international raiders…</div>';Promise.all(waits).then(draw);return}draw()}
 const oldRender=window.render;window.render=function(v='dashboard'){if(v==='international'){show();return}return oldRender(v)};const oldOpen=window.openView;window.openView=function(v){if(v==='international'){show();return}return oldOpen(v)};
 document.addEventListener('click',e=>{const nav=e.target.closest('#nav button[data-view="international"]');if(nav){e.preventDefault();e.stopImmediatePropagation();show();return}const f=e.target.closest('[data-ir]');if(f){document.querySelectorAll('[data-ir]').forEach(x=>x.classList.remove('active'));f.classList.add('active');irFilter=f.dataset.ir;paint()}},true);document.addEventListener('input',e=>{if(e.target?.id==='ir-search'){irQuery=e.target.value;paint()}});document.addEventListener('change',e=>{if(e.target?.id==='ir-sort'){irSort=e.target.value;paint()}});
})();