// Lead-up Tracker — approved compact workspace standard, backed by complete form history.
(function(){
 let lf='all',lq='';
 const code=h=>({AU:'AUS',AUS:'AUS',NZ:'NZ',IE:'IRE',IRE:'IRE',UK:'GB',GB:'GB',FR:'FR',JP:'JPN',JPN:'JPN',US:'USA',USA:'USA'}[String(h?.country||'').toUpperCase()]||h?.country||'—');
 const num=v=>(v!==null&&v!==undefined&&v!==''&&Number.isFinite(Number(v)))?Number(v):null;
 const evs=()=>[...(leadupData?.events||[])].sort((a,b)=>String(b.date||'').localeCompare(String(a.date||''))||String(a.horse||'').localeCompare(String(b.horse||'')));
 function formRuns(name){try{const raw=typeof publicActualRuns==='function'?publicActualRuns(name):(formIntelData?.horses?.[name]?.runs||[]);return [...raw].filter(r=>r&&r.date).sort((a,b)=>String(b.date||'').localeCompare(String(a.date||'')))}catch(_){return []}}
 function latestTracked(name){return evs().find(e=>e.horse===name)||null}
 function latest(name){const e=latestTracked(name),r=formRuns(name)[0]||null;if(e&&(!r||String(e.date||'')>=String(r.date||'')))return {...e,_kind:'event'};if(r)return {horse:name,date:r.date,race:r.race||r.raceName||r.event||'—',track:r.track||r.venue||'—',distanceM:num(r.distanceM)??num(r.distance),result:r.finish||r.position||'—',status:r.classGroup||r.class||r.grade||'FORM',note:r.going?`Going: ${r.going}`:'Latest loaded race form',_run:r,_kind:'form'};return e}
 function status(e){if(!e)return '<span class="lu-status neutral">NO FORM</span>';const s=e.status||'Form',c=/golden|group 1|winner/i.test(s)?'green':/did not|failed/i.test(s)?'red':/declared|due/i.test(s)?'blue':'neutral';return `<span class="lu-status ${c}">${String(s).toUpperCase()}</span>`}
 function date(e){if(!e?.date)return '—';return new Date(e.date+'T00:00:00').toLocaleDateString('en-AU',{day:'numeric',month:'short'})}
 function rows(){let a=(cupData?.horses||[]).map(h=>({h,e:latest(h.horse)}));if(lf==='tracked')a=a.filter(x=>x.e);else if(lf==='pending')a=a.filter(x=>x.e&&['Declared','Due to race'].includes(x.e.status));else if(lf==='international')a=a.filter(x=>x.h.trainingRegion==='International');else if(lf==='tickets')a=a.filter(x=>latestTracked(x.h.horse)?.status==='Golden Ticket');if(lq)a=a.filter(x=>`${x.h.horse} ${x.h.trainer} ${x.e?.race||''} ${x.e?.track||''}`.toLowerCase().includes(lq.toLowerCase()));return a.sort((a,b)=>(b.e?.date||'').localeCompare(a.e?.date||'')||a.h.horse.localeCompare(b.h.horse))}
 function metrics(){const a=cupData?.horses||[],events=evs(),tracked=a.filter(h=>latest(h.horse)).length,pending=events.filter(e=>['Declared','Due to race'].includes(e.status)).length,results=a.filter(h=>latest(h.horse)?._kind==='form'||events.some(e=>e.horse===h.horse&&e.type==='Result')).length,tickets=events.filter(e=>e.status==='Golden Ticket').length;return {n:a.length,tracked,pending,results,tickets}}
 window.leadupsProView=function(){const m=metrics();return `<div class="section-header lu-head"><div><div class="kicker">FLEMINGTON · 3200M · GROUP 1</div><h2>Lead-up Tracker</h2></div></div><section class="lu-summary"><div><span>NOMINEES</span><strong>${m.n}</strong><small>Complete Cup universe</small></div><div><span>FORM LOADED</span><strong>${m.tracked}</strong><small>Horses with latest race form</small></div><div><span>LATEST RUNS</span><strong>${m.results}</strong><small>Race form represented</small></div><div><span>PENDING STARTS</span><strong>${m.pending}</strong><small>Declared engagements</small></div><div><span>GOLDEN TICKETS</span><strong>${m.tickets}</strong><small>Tracked qualifying wins</small></div></section><div class="toolbar lu-toolbar"><div class="filters"><button class="filter active" data-lu="all">All Horses <span>101</span></button><button class="filter" data-lu="tracked">With Form</button><button class="filter" data-lu="pending">Pending</button><button class="filter" data-lu="tickets">Golden Tickets</button><button class="filter" data-lu="international">International</button></div><input id="lu-search" class="search" placeholder="Search horse, trainer, race or track…"></div><div class="panel lu-panel"><div class="lu-panel-head"><div><h3>101-Horse Campaign Board</h3><p>Latest known race or campaign event for every Melbourne Cup nominee.</p></div><span id="lu-count">101 horses</span></div><div class="table-wrap"><table class="data-table lu-table"><thead><tr><th>#</th><th>Horse</th><th>Country</th><th>Trainer</th><th>Date</th><th>Latest Lead-up / Run</th><th>Track</th><th>Dist</th><th>Going</th><th>Result</th><th>PFR</th><th>Status / Class</th></tr></thead><tbody id="lu-body"></tbody></table></div></div>`}
 window.paintLeadupsPro=function(){const a=rows(),b=document.getElementById('lu-body');if(!b)return;b.innerHTML=a.map((x,i)=>{const r=x.e?._run||null;let pfr=num(r?.publicRating)??num(r?.pfr)??num(r?.rating);if(pfr==null&&r&&typeof publicRunRating==='function'){try{pfr=num(publicRunRating(r))}catch(_){}}return `<tr><td>${i+1}</td><td class="horse">${typeof silkHorse==='function'?silkHorse(x.h.horse):horseLink(x.h.horse)}</td><td>${code(x.h)}</td><td>${x.h.trainer||'—'}</td><td>${date(x.e)}</td><td class="lu-race">${x.e?.race||'—'}</td><td>${x.e?.track||'—'}</td><td>${x.e?.distanceM?Math.round(x.e.distanceM)+'m':'—'}</td><td>${r?.going||'—'}</td><td><strong>${x.e?.result||'—'}</strong></td><td>${pfr!=null?pfr.toFixed(1):'—'}</td><td>${status(x.e)}</td></tr>`}).join('');document.getElementById('lu-count').textContent=`Showing ${a.length} of 101 horses`}
 function show(){currentView='leadups';selectedHorse=null;document.querySelectorAll('#nav button[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view==='leadups'));document.getElementById('page-title').textContent='Lead-up Tracker';const root=document.getElementById('app-content');const ready=()=>{root.innerHTML=leadupsProView();paintLeadupsPro()};if(!leadupData||!formIntelData){root.innerHTML='<div class="placeholder">Loading complete lead-up form…</div>';Promise.all([typeof loadLeadups==='function'?loadLeadups():Promise.resolve(),typeof loadFormIntel==='function'?loadFormIntel():Promise.resolve()]).then(ready);return}ready()}
 const baseRender=window.render;window.render=function(v='dashboard'){if(v==='leadups'){show();return}return baseRender(v)};
 const baseOpen=window.openView;window.openView=function(v){if(v==='leadups'){show();return}return baseOpen(v)};
 document.addEventListener('click',e=>{const n=e.target.closest('#nav button[data-view="leadups"]');if(n){e.preventDefault();e.stopImmediatePropagation();show();return}const f=e.target.closest('[data-lu]');if(f){document.querySelectorAll('[data-lu]').forEach(x=>x.classList.remove('active'));f.classList.add('active');lf=f.dataset.lu;paintLeadupsPro()}},true);
 document.addEventListener('input',e=>{if(e.target?.id==='lu-search'){lq=e.target.value;paintLeadupsPro()}});
})();