// Lead-up Tracker — approved compact workspace standard.
(function(){
 let lf='all',lq='';
 const code=h=>({AU:'AUS',AUS:'AUS',NZ:'NZ',IE:'IRE',IRE:'IRE',UK:'GB',GB:'GB',FR:'FR',JP:'JPN',JPN:'JPN'}[String(h?.country||'').toUpperCase()]||h?.country||'—');
 const evs=()=>[...(leadupData?.events||[])].sort((a,b)=>String(b.date).localeCompare(String(a.date))||a.horse.localeCompare(b.horse));
 function latest(name){return evs().find(e=>e.horse===name)||null}
 function status(e){if(!e)return '<span class="lu-status neutral">NO EVENT</span>';const s=e.status||'Tracked',c=/golden|group 1/i.test(s)?'green':/did not|failed/i.test(s)?'red':/declared|due/i.test(s)?'blue':'neutral';return `<span class="lu-status ${c}">${s.toUpperCase()}</span>`}
 function date(e){if(!e?.date)return '—';return new Date(e.date+'T00:00:00').toLocaleDateString('en-AU',{day:'numeric',month:'short'})}
 function rows(){let a=(cupData?.horses||[]).map(h=>({h,e:latest(h.horse)}));if(lf==='tracked')a=a.filter(x=>x.e);else if(lf==='pending')a=a.filter(x=>x.e&&['Declared','Due to race'].includes(x.e.status));else if(lf==='international')a=a.filter(x=>x.h.trainingRegion==='International');else if(lf==='tickets')a=a.filter(x=>x.e?.status==='Golden Ticket');if(lq)a=a.filter(x=>`${x.h.horse} ${x.h.trainer} ${x.e?.race||''} ${x.e?.track||''}`.toLowerCase().includes(lq.toLowerCase()));return a.sort((a,b)=>(b.e?.date||'').localeCompare(a.e?.date||'')||a.h.horse.localeCompare(b.h.horse))}
 function metrics(){const a=cupData?.horses||[],events=evs(),tracked=new Set(events.map(e=>e.horse)).size,pending=events.filter(e=>['Declared','Due to race'].includes(e.status)).length,results=events.filter(e=>e.type==='Result').length,tickets=events.filter(e=>e.status==='Golden Ticket').length;return {n:a.length,tracked,pending,results,tickets}}
 window.leadupsProView=function(){const m=metrics();return `<div class="section-header lu-head"><div><div class="kicker">FLEMINGTON · 3200M · GROUP 1</div><h2>Lead-up Tracker</h2></div></div><section class="lu-summary"><div><span>NOMINEES</span><strong>${m.n}</strong><small>Complete Cup universe</small></div><div><span>CAMPAIGNS TRACKED</span><strong>${m.tracked}</strong><small>Horses with dated activity</small></div><div><span>RESULTS</span><strong>${m.results}</strong><small>Completed lead-up runs</small></div><div><span>PENDING STARTS</span><strong>${m.pending}</strong><small>Declared engagements</small></div><div><span>GOLDEN TICKETS</span><strong>${m.tickets}</strong><small>Tracked qualifying wins</small></div></section><div class="toolbar lu-toolbar"><div class="filters"><button class="filter active" data-lu="all">All Horses <span>101</span></button><button class="filter" data-lu="tracked">Tracked</button><button class="filter" data-lu="pending">Pending</button><button class="filter" data-lu="tickets">Golden Tickets</button><button class="filter" data-lu="international">International</button></div><input id="lu-search" class="search" placeholder="Search horse, trainer, race or track…"></div><div class="panel lu-panel"><div class="lu-panel-head"><div><h3>101-Horse Campaign Board</h3><p>Latest tracked lead-up for every Melbourne Cup nominee.</p></div><span id="lu-count">101 horses</span></div><div class="table-wrap"><table class="data-table lu-table"><thead><tr><th>#</th><th>Horse</th><th>Country</th><th>Trainer</th><th>Date</th><th>Latest Lead-up / Event</th><th>Track</th><th>Dist</th><th>Result</th><th>Status</th><th>Campaign Note</th></tr></thead><tbody id="lu-body"></tbody></table></div></div>`}
 window.paintLeadupsPro=function(){const a=rows(),b=document.getElementById('lu-body');if(!b)return;b.innerHTML=a.map((x,i)=>`<tr><td>${i+1}</td><td class="horse">${typeof silkHorse==='function'?silkHorse(x.h.horse):horseLink(x.h.horse)}</td><td>${code(x.h)}</td><td>${x.h.trainer||'—'}</td><td>${date(x.e)}</td><td class="lu-race">${x.e?.race||'—'}</td><td>${x.e?.track||'—'}</td><td>${x.e?.distanceM?x.e.distanceM+'m':'—'}</td><td><strong>${x.e?.result||'—'}</strong></td><td>${status(x.e)}</td><td class="lu-note">${x.e?.note||'—'}</td></tr>`).join('');document.getElementById('lu-count').textContent=`Showing ${a.length} of 101 horses`}
 function show(){currentView='leadups';selectedHorse=null;document.querySelectorAll('#nav button[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view==='leadups'));document.getElementById('page-title').textContent='Lead-up Tracker';const root=document.getElementById('app-content');if(!leadupData){root.innerHTML='<div class="placeholder">Loading lead-up tracker…</div>';loadLeadups().then(show);return}root.innerHTML=leadupsProView();paintLeadupsPro()}
 const baseRender=window.render;window.render=function(v='dashboard'){if(v==='leadups'){show();return}return baseRender(v)};
 const baseOpen=window.openView;window.openView=function(v){if(v==='leadups'){show();return}return baseOpen(v)};
 document.addEventListener('click',e=>{const n=e.target.closest('#nav button[data-view="leadups"]');if(n){e.preventDefault();e.stopImmediatePropagation();show();return}const f=e.target.closest('[data-lu]');if(f){document.querySelectorAll('[data-lu]').forEach(x=>x.classList.remove('active'));f.classList.add('active');lf=f.dataset.lu;paintLeadupsPro()}},true);
 document.addEventListener('input',e=>{if(e.target?.id==='lu-search'){lq=e.target.value;paintLeadupsPro()}});
})();