// Markets — approved premium 101-horse market workspace.
(function(){
 function U(){return typeof marketUniverse==='function'?marketUniverse():[]}
 function horse(n){return horseByName(n)||{horse:n,trainer:'—',country:'—'};}
 function code(h){const m={AU:'AUS',AUS:'AUS',NZ:'NZ',IE:'IRE',IRE:'IRE',UK:'GB',GB:'GB',FR:'FR',JP:'JPN',JPN:'JPN',US:'USA',USA:'USA'};const x=String(h.country||'').toUpperCase();return m[x]||x||'—';}
 function current(r){return r?.last?.odds?Number(r.last.odds):null;}
 function move(r){if(!r?.previousSameBook||!r.last)return null;return ((100/r.last.odds-100/r.previousSameBook.odds)/(100/r.previousSameBook.odds))*100;}
 function movers(){return U().filter(r=>move(r)!==null).sort((a,b)=>Math.abs(move(b))-Math.abs(move(a)));}
 function price(v){return Number.isFinite(v)?`$${v.toFixed(2)}`:'—';}
 function trend(r){const m=move(r);if(m===null)return '<span class="mk-flat">—</span>';const firm=m>0;return `<span class="mk-move ${firm?'firm':'drift'}">${firm?'▼':'▲'} ${Math.abs(m).toFixed(0)}%</span>`;}
 function status(r){const m=move(r);if(m===null)return '<span class="mk-trend flat">Stable</span>';return m>0?'<span class="mk-trend firm">Firming</span>':'<span class="mk-trend drift">Drifting</span>';}
 function spark(r){const pts=(r.points||[]).slice(-8);if(pts.length<2)return '<span class="mk-spark-empty">—</span>';const vals=pts.map(x=>Number(x.odds)),lo=Math.min(...vals),hi=Math.max(...vals),span=hi-lo||1;const xy=vals.map((v,i)=>`${Math.round(i*68/(vals.length-1))},${Math.round(22-(v-lo)*18/span)}`).join(' ');const cls=(move(r)||0)>=0?'firm':'drift';return `<svg class="mk-spark ${cls}" viewBox="0 0 70 24"><polyline points="${xy}"/></svg>`;}
 function sortedRows(){return U().slice().sort((a,b)=>(current(a)??99999)-(current(b)??99999)||a.horse.localeCompare(b.horse));}
 window.marketsProView=function(){const rows=sortedRows(),ms=movers(),firm=ms.filter(r=>move(r)>0)[0],drift=ms.filter(r=>move(r)<0)[0];return `<div class="mk-head"><div><div class="kicker">FLEMINGTON · 3200M · GROUP 1</div><h2>Melbourne Cup Markets</h2><p>Live and historical prices from selected bookmakers. 101 nominees.</p></div><div class="mk-updated"><span>Last updated</span><strong>${new Date().toLocaleDateString('en-AU',{day:'2-digit',month:'short',year:'numeric'})}</strong></div></div><section class="mk-summary"><div><span>MARKET STATUS</span><strong><i></i> Live</strong><small>Prices updating</small></div><div><span>BIGGEST FIRM</span><strong>${firm?.horse||'—'}</strong><small>${firm?`${price(firm.previousSameBook.odds)} → ${price(firm.last.odds)}　▼ ${Math.abs(move(firm)).toFixed(0)}%`:'—'}</small></div><div><span>BIGGEST DRIFT</span><strong>${drift?.horse||'—'}</strong><small>${drift?`${price(drift.previousSameBook.odds)} → ${price(drift.last.odds)}　▲ ${Math.abs(move(drift)).toFixed(0)}%`:'—'}</small></div></section><section class="mk-movers"><div class="mk-section-title"><strong>Top Market Movers (24h)</strong></div><div class="mk-mover-grid">${ms.slice(0,6).map(r=>`<div class="mk-mover ${move(r)>0?'firm':'drift'}"><strong>${r.horse}</strong><span>${price(r.previousSameBook.odds)} → ${price(r.last.odds)}</span>${trend(r)}</div>`).join('')}</div></section><div class="mk-toolbar"><input id="mk-search" class="search" placeholder="Search horse or trainer…"><div class="filters"><button class="filter active" data-mk="all">All Horses <span>101</span></button><button class="filter" data-mk="top20">Top 20</button><button class="filter" data-mk="top50">Top 50</button><button class="filter" data-mk="international">International</button><button class="filter" data-mk="movers">Market Movers</button></div><select id="mk-sort" class="mk-select"><option value="odds">Sort: Current Odds</option><option value="az">Sort A–Z</option><option value="move">Sort: Biggest Move</option></select></div><div class="panel mk-board"><div class="mk-board-head"><div><h3>Market Board (101 Horses)</h3><p>Current fixed win prices, implied probabilities and market movement. Click a horse for full profile.</p></div><span id="mk-count">101 horses</span></div><div class="table-wrap"><table class="data-table mk-table"><thead><tr><th>#</th><th>Horse</th><th>Country</th><th>Trainer</th><th>Current Odds</th><th>Move</th><th>Implied</th><th>Price History</th><th>High / Low</th><th>Market Trend</th></tr></thead><tbody id="mk-body"></tbody></table></div></div>`;};
 window.paintMarketsPro=function(filter='all',q='',sort='odds'){let rows=sortedRows();const query=q.trim().toLowerCase();if(filter==='top20')rows=rows.slice(0,20);else if(filter==='top50')rows=rows.slice(0,50);else if(filter==='international')rows=rows.filter(r=>horse(r.horse).trainingRegion==='International');else if(filter==='movers')rows=rows.filter(r=>Math.abs(move(r)||0)>=10);if(query)rows=rows.filter(r=>`${r.horse} ${horse(r.horse).trainer}`.toLowerCase().includes(query));if(sort==='az')rows.sort((a,b)=>a.horse.localeCompare(b.horse));else if(sort==='move')rows.sort((a,b)=>Math.abs(move(b)||0)-Math.abs(move(a)||0));const body=document.getElementById('mk-body');if(!body)return;body.innerHTML=rows.map((r,i)=>{const h=horse(r.horse),o=current(r),vals=(r.points||[]).map(x=>Number(x.odds)).filter(Number.isFinite),hi=vals.length?Math.max(...vals):null,lo=vals.length?Math.min(...vals):null;return `<tr onclick="openHorse('${r.horse.replace(/'/g,"\\'")}')"><td>${i+1}</td><td class="horse">${typeof silkHorse==='function'?silkHorse(r.horse):horseLink(r.horse)}</td><td>${code(h)}</td><td>${h.trainer||'—'}</td><td class="mk-odds">${price(o)}</td><td>${trend(r)}</td><td>${o?(100/o).toFixed(1)+'%':'—'}</td><td>${spark(r)}</td><td>${hi?`${price(hi)} / ${price(lo)}`:'—'}</td><td>${status(r)}</td></tr>`}).join('');document.getElementById('mk-count').textContent=`Showing ${rows.length} of 101 horses`;};
 function state(){return {f:document.querySelector('[data-mk].active')?.dataset.mk||'all',q:document.getElementById('mk-search')?.value||'',s:document.getElementById('mk-sort')?.value||'odds'};}function repaint(){const x=state();paintMarketsPro(x.f,x.q,x.s);}
 document.addEventListener('click',e=>{const b=e.target.closest('[data-mk]');if(!b)return;document.querySelectorAll('[data-mk]').forEach(x=>x.classList.remove('active'));b.classList.add('active');repaint();});document.addEventListener('input',e=>{if(e.target?.id==='mk-search')repaint();});document.addEventListener('change',e=>{if(e.target?.id==='mk-sort')repaint();});
 function show(){currentView='markets';document.querySelectorAll('#nav button[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view==='markets'));document.getElementById('page-title').textContent='Markets';const root=document.getElementById('app-content'),go=()=>{root.innerHTML=marketsProView();paintMarketsPro();};if(!marketWorkbenchPromise){root.innerHTML='<div class="placeholder">Loading market workspace…</div>';loadMarketWorkbench().then(go);}else go();}
 const old=window.openView;window.openView=function(v){if(v==='markets'){show();return;}return old.apply(this,arguments);};document.addEventListener('click',e=>{if(!e.target.closest('#nav button[data-view="markets"]'))return;e.preventDefault();e.stopImmediatePropagation();show();},true);
})();