// Nominations — approved premium racing workspace standard.
(function(){
  if(typeof nominationsView!=='function'||typeof paintNominations!=='function')return;
  const countryMap={AUS:['🇦🇺','AUS'],AU:['🇦🇺','AUS'],NZ:['🇳🇿','NZ'],IRE:['🇮🇪','IRE'],IE:['🇮🇪','IRE'],GB:['🇬🇧','GB'],UK:['🇬🇧','GB'],FR:['🇫🇷','FR'],JPN:['🇯🇵','JPN'],JP:['🇯🇵','JPN'],USA:['🇺🇸','USA'],US:['🇺🇸','USA'],GER:['🇩🇪','GER'],DE:['🇩🇪','GER']};
  function countryCell(h){const raw=String(h.country||'').toUpperCase();const c=countryMap[raw]||['',raw||'—'];return `<span class="nom-country"><span class="nom-flag-img" aria-hidden="true">${c[0]}</span><span>${c[1]}</span></span>`;}
  function marketRec(h){return typeof marketUniverse==='function'?marketUniverse().find(x=>x.horse===h.horse):null;}
  function nomMarket(h){const m=marketRec(h);const odds=Number(m?.last?.odds??h.marketOdds);if(!Number.isFinite(odds)||odds<=1)return '—';const cls=odds<=15?'short':odds>=201?'long':'mid';return `<span class="nom-market ${cls}">$${odds.toFixed(2)}</span>`;}
  function nomWeight(h){const official=typeof orderOfficialWeight==='function'?orderOfficialWeight(h.horse):null;if(Number.isFinite(official))return official.toFixed(1);const w=typeof weightRec==='function'?weightRec(h.horse):null;return w&&Number.isFinite(Number(w.predictedKg))?Number(w.predictedKg).toFixed(1):'—';}
  function nomPfr(h){const r=typeof publicFormRating==='function'?publicFormRating(h.horse):null;return r&&Number.isFinite(Number(r.current))?Number(r.current).toFixed(1):'—';}
  function nomLens(h){const x=typeof cupPublicLens==='function'?cupPublicLens(h.horse):null;return x&&Number.isFinite(Number(x.score))?Number(x.score).toFixed(1):'—';}
  function nomLastRun(h){const runs=typeof publicRatedRuns==='function'?publicRatedRuns(h.horse):[];const r=runs[0];return r?`${r.finish||'—'} - ${r.race||'—'}`:'—';}
  function cleanBase(h){const v=typeof currentBase==='function'?currentBase(h.horse):null;return !v||v==='Researching'?'—':String(v).replace(/HORSE-SPECIFIC CURRENT/gi,'').replace(/TRAINER BASE FALLBACK/gi,'').trim();}
  function nomStatus(h){return GOLDEN_TICKETS.has(h.horse)?'<span class="nom-status qualified">QUALIFIED</span>':'<span class="nom-status">NOMINATED</span>';}
  nominationsView=function(){return `<div class="nom-page-head"><div><div class="kicker">FLEMINGTON · 3200M · GROUP 1</div><h2>Nominations</h2></div><div class="nom-race-meta"><span class="nom-cup">🏆</span><div><strong>Final Field</strong><small>3 Nov 2026 · Flemington</small></div><b>${Math.max(0,Math.ceil((new Date('2026-11-03T15:00:00+11:00')-Date.now())/86400000))}<em>DAYS TO RACE</em></b></div></div><div class="toolbar nom-toolbar"><div class="filters"><button class="filter active" data-nom-filter="all">All Nominations <span>101</span></button><button class="filter" data-nom-filter="Australasia">Australasian <span>78</span></button><button class="filter" data-nom-filter="International">International <span>23</span></button><button class="filter" data-nom-filter="ticket">Qualified <span>${[...(GOLDEN_TICKETS||[])].filter(x=>horseByName(x)).length||6}</span></button></div><input id="nom-search" class="search" type="search" placeholder="Search horse, trainer or country…"></div><div class="panel nom-table-panel"><div class="table-wrap"><table class="data-table nominations-table"><thead><tr><th>#</th><th>Horse</th><th>Country</th><th>Trainer</th><th>Training Base</th><th>Weight (kg)</th><th>PFR</th><th>Last Run</th><th>Market</th><th>Cup Lens</th><th>Status</th></tr></thead><tbody id="nom-body"></tbody></table></div></div>`;};
  paintNominations=function(filter='all',query=''){const tbody=document.getElementById('nom-body');if(!tbody)return;const q=query.trim().toLowerCase();const rows=(cupData?.horses??[]).filter(h=>{const region=filter==='all'||h.trainingRegion===filter||(filter==='ticket'&&GOLDEN_TICKETS.has(h.horse));return region&&(!q||`${h.horse} ${h.trainer} ${h.country} ${cleanBase(h)}`.toLowerCase().includes(q));});tbody.innerHTML=rows.map(h=>`<tr><td>${h.nominationNumber}</td><td class="horse"><span class="nom-silk">${typeof silkForHorse==='function'?silkForHorse(h.horse):''}</span>${horseLink(h.horse)}${GOLDEN_TICKETS.has(h.horse)?'<span class="ticket-dot">★</span>':''}</td><td>${countryCell(h)}</td><td>${h.trainer}</td><td class="nom-base">${cleanBase(h)}</td><td class="nom-num">${nomWeight(h)}</td><td class="nom-pfr">${nomPfr(h)}</td><td class="nom-last">${nomLastRun(h)}</td><td>${nomMarket(h)}</td><td class="nom-lens">${nomLens(h)}</td><td>${nomStatus(h)}</td></tr>`).join('');};
})();