// Nominations — approved premium racing workspace standard.
(function(){
  if(typeof nominationsView!=='function'||typeof paintNominations!=='function')return;
  const flags={AUS:'🇦🇺',NZ:'🇳🇿',IRE:'🇮🇪',GB:'🇬🇧',FR:'🇫🇷',JPN:'🇯🇵',USA:'🇺🇸',GER:'🇩🇪'};
  function marketRec(h){return typeof marketUniverse==='function'?marketUniverse().find(x=>x.horse===h.horse):null;}
  function nomMarket(h){const m=marketRec(h);const odds=m?.last?.odds??h.marketOdds;return Number.isFinite(Number(odds))?`<span class="nom-market">$${Number(odds).toFixed(2)}</span>`:'—';}
  function nomWeight(h){const official=typeof orderOfficialWeight==='function'?orderOfficialWeight(h.horse):null;if(Number.isFinite(official))return `${official.toFixed(1)}`;const w=typeof weightRec==='function'?weightRec(h.horse):null;return w&&Number.isFinite(Number(w.predictedKg))?`${Number(w.predictedKg).toFixed(1)}`:'—';}
  function nomPfr(h){const r=typeof publicFormRating==='function'?publicFormRating(h.horse):null;return r?Number(r.current).toFixed(1):'—';}
  function nomLens(h){const x=typeof cupPublicLens==='function'?cupPublicLens(h.horse):null;return x?Number(x.score).toFixed(1):'—';}
  function nomLastRun(h){const runs=typeof publicRatedRuns==='function'?publicRatedRuns(h.horse):[];const r=runs[0];return r?`${r.finish||'—'} · ${r.race||'—'}`:'—';}
  function cleanBase(h){const v=currentBase(h.horse);return !v||v==='Researching'?'—':String(v).replace(/HORSE-SPECIFIC CURRENT/gi,'').replace(/TRAINER BASE FALLBACK/gi,'').trim();}
  function nomStatus(h){return GOLDEN_TICKETS.has(h.horse)?tag('QUALIFIED','green'):tag('NOMINATED','green');}
  nominationsView=function(){return `<div class="section-header"><div><div class="kicker">MELBOURNE CUP 2026</div><h2>Nominations</h2></div></div><div class="toolbar"><input id="nom-search" class="search" type="search" placeholder="Search horse or trainer…"><div class="filters"><button class="filter active" data-nom-filter="all">All Nominations</button><button class="filter" data-nom-filter="Australasia">Australasian</button><button class="filter" data-nom-filter="International">International</button><button class="filter" data-nom-filter="ticket">Qualified</button></div></div><div class="panel"><div class="table-wrap"><table class="data-table nominations-table"><thead><tr><th>#</th><th>Horse</th><th>Country</th><th>Trainer</th><th>Training Base</th><th>Weight (kg)</th><th>PFR</th><th>Last Run</th><th>Market</th><th>Cup Lens</th><th>Status</th></tr></thead><tbody id="nom-body"></tbody></table></div></div>`;};
  paintNominations=function(filter='all',query=''){const tbody=document.getElementById('nom-body');if(!tbody)return;const q=query.trim().toLowerCase();const rows=(cupData?.horses??[]).filter(h=>{const region=filter==='all'||h.trainingRegion===filter||(filter==='ticket'&&GOLDEN_TICKETS.has(h.horse));return region&&(!q||`${h.horse} ${h.trainer} ${h.country} ${cleanBase(h)}`.toLowerCase().includes(q));});tbody.innerHTML=rows.map(h=>`<tr><td>${h.nominationNumber}</td><td class="horse">${horseLink(h.horse)}${GOLDEN_TICKETS.has(h.horse)?'<span class="ticket-dot">★</span>':''}</td><td><span class="nom-flag">${flags[h.country]||''}</span>${h.country}</td><td>${h.trainer}</td><td class="nom-base">${cleanBase(h)}</td><td><strong>${nomWeight(h)}</strong></td><td class="nom-pfr">${nomPfr(h)}</td><td class="nom-last">${nomLastRun(h)}</td><td>${nomMarket(h)}</td><td class="nom-lens">${nomLens(h)}</td><td>${nomStatus(h)}</td></tr>`).join('');};
})();
