// Order of Entry — premium consumer-facing workspace.
(function(){
 function allRows(){const d=projectedFieldData||{},inMap=new Map((d.projected24||[]).map(x=>[x.horse,x])),next=new Map((d.nextSix||[]).map((n,i)=>[n,{rank:25+i,horse:n,band:'Next six'}]));return (cupData?.horses||[]).map(h=>{const p=inMap.get(h.horse)||next.get(h.horse)||null;return {h,p,rank:p?.rank??null,projected:!!inMap.get(h.horse),qualified:GOLDEN_TICKETS.has(h.horse)};}).sort((a,b)=>(a.rank??999)-(b.rank??999)||a.h.horse.localeCompare(b.h.horse));}
 function wt(n){const o=typeof orderOfficialWeight==='function'?orderOfficialWeight(n):null,p=typeof orderPredWeight==='function'?orderPredWeight(n):null;const v=Number.isFinite(o)?o:p;return Number.isFinite(v)?v.toFixed(1):'—';}
 function pfr(n){const r=typeof publicFormRating==='function'?publicFormRating(n):null;return Number.isFinite(Number(r?.current))?Number(r.current).toFixed(1):'—';}
 function market(h){const m=typeof marketUniverse==='function'?marketUniverse().find(x=>x.horse===h.horse):null,o=Number(m?.last?.odds??h.marketOdds);return Number.isFinite(o)&&o>1?`$${o.toFixed(2)}`:'—';}
 function country(h){const m={AU:'AUS',AUS:'AUS',NZ:'NZ',IE:'IRE',IRE:'IRE',UK:'GB',GB:'GB',FR:'FR',JP:'JPN',JPN:'JPN',US:'USA',USA:'USA'};return m[String(h.country||'').toUpperCase()]||h.country||'—';}
 function band(x){if(x.qualified)return '<span class="oe-state qualified">QUALIFIED</span>';if(x.projected)return x.rank<=19?'<span class="oe-state strong">PROJECTED IN</span>':'<span class="oe-state bubble">BUBBLE</span>';if(x.rank)return '<span class="oe-state out">NEXT IN LINE</span>';return '<span class="oe-state neutral">NOMINATED</span>';}
 window.orderProView=function(){const rs=allRows(),q=rs.filter(x=>x.qualified).length,in24=rs.filter(x=>x.projected).length,firstOut=rs.find(x=>x.rank===25)?.h.horse||'—';return `<div class="section-header oe-head"><div><div class="kicker">FLEMINGTON · 3200M · GROUP 1</div><h2>Order of Entry</h2></div></div><section class="oe-summary"><div><span>NOMINATIONS</span><strong>${rs.length}</strong></div><div><span>PROJECTED FIELD</span><strong>${in24}<small> / 24</small></strong></div><div><span>QUALIFIED</span><strong>${q}</strong></div><div><span>FIRST OUT</span><strong class="oe-name">${firstOut}</strong></div></section><div class="toolbar oe-toolbar"><div class="filters"><button class="filter active" data-oe="all">All Horses <span>${rs.length}</span></button><button class="filter" data-oe="in">Projected 24 <span>${in24}</span></button><button class="filter" data-oe="qualified">Qualified <span>${q}</span></button><button class="filter" data-oe="international">International <span>${rs.filter(x=>x.h.trainingRegion==='International').length}</span></button></div><input id="oe-search" class="search" placeholder="Search horse or trainer…"></div><div class="panel oe-panel"><div class="table-wrap"><table class="data-table oe-table"><thead><tr><th>Proj.</th><th>Horse</th><th>Country</th><th>Trainer</th><th>Weight</th><th>PFR</th><th>Market</th><th>Position</th><th>Status</th></tr></thead><tbody id="oe-body"></tbody></table></div></div>`;};
 window.paintOrderPro=function(filter='all',query=''){const body=document.getElementById('oe-body');if(!body)return;const q=query.trim().toLowerCase();const rs=allRows().filter(x=>(filter==='all'||filter==='in'&&x.projected||filter==='qualified'&&x.qualified||filter==='international'&&x.h.trainingRegion==='International')&&(!q||`${x.h.horse} ${x.h.trainer}`.toLowerCase().includes(q)));body.innerHTML=rs.map(x=>`<tr class="${x.rank===24?'oe-cut':''} ${x.rank===25?'oe-firstout':''}"><td class="oe-rank">${x.rank?`#${x.rank}`:'—'}</td><td class="horse">${typeof silkHorse==='function'?silkHorse(x.h.horse):horseLink(x.h.horse)}</td><td>${country(x.h)}</td><td>${x.h.trainer}</td><td class="oe-num">${wt(x.h.horse)}</td><td class="oe-num">${pfr(x.h.horse)}</td><td>${market(x.h)}</td><td>${x.projected?(x.rank===24?'CUT LINE':x.rank<=19?'IN':'BUBBLE'):x.rank===25?'FIRST OUT':x.rank?'CHASER':'—'}</td><td>${band(x)}</td></tr>`).join('');};
 document.addEventListener('click',e=>{const b=e.target.closest('[data-oe]');if(!b)return;document.querySelectorAll('[data-oe]').forEach(x=>x.classList.remove('active'));b.classList.add('active');paintOrderPro(b.dataset.oe,document.getElementById('oe-search')?.value||'');});
 document.addEventListener('input',e=>{if(e.target?.id==='oe-search')paintOrderPro(document.querySelector('[data-oe].active')?.dataset.oe||'all',e.target.value);});
 const base=window.openView;window.openView=function(view){if(view==='order'){currentView='order';document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view==='order'));document.getElementById('page-title').textContent='Order of Entry';const root=document.getElementById('app-content');const go=()=>{root.innerHTML=orderProView();paintOrderPro();};if(!projectedFieldData){root.innerHTML='<div class="placeholder">Loading…</div>';Promise.all([typeof loadProjectedField==='function'?loadProjectedField():Promise.resolve(),typeof loadExtras==='function'?loadExtras():Promise.resolve()]).then(go);}else go();return;}return base.apply(this,arguments);};
})();