// Order of Entry — full 101-horse premium card workspace.
(function(){
 function allRows(){const d=projectedFieldData||{},inside=new Map((d.projected24||[]).map(x=>[x.horse,x])),next=new Map((d.nextSix||[]).map((n,i)=>[n,{rank:25+i,horse:n,band:'Next six'}]));return (cupData?.horses||[]).map(h=>{const p=inside.get(h.horse)||next.get(h.horse)||null;return {h,p,rank:p?.rank??null,projected:inside.has(h.horse),qualified:GOLDEN_TICKETS.has(h.horse)};}).sort((a,b)=>(a.rank??999)-(b.rank??999)||a.h.horse.localeCompare(b.h.horse));}
 function wt(n){const o=typeof orderOfficialWeight==='function'?orderOfficialWeight(n):null,p=typeof orderPredWeight==='function'?orderPredWeight(n):null,v=Number.isFinite(o)?o:p;return Number.isFinite(v)?v.toFixed(1):'—';}
 function pfr(n){const r=typeof publicFormRating==='function'?publicFormRating(n):null;return Number.isFinite(Number(r?.current))?Number(r.current).toFixed(1):'—';}
 function marketRaw(h){const m=typeof marketUniverse==='function'?marketUniverse().find(x=>x.horse===h.horse):null,o=Number(m?.last?.odds??h.marketOdds);return Number.isFinite(o)&&o>1?o:null;}
 function market(h){const o=marketRaw(h);if(!o)return '—';const cls=o<=15?'short':o>=201?'long':'mid';return `<span class="oe-price ${cls}">$${o.toFixed(2)}</span>`;}
 function country(h){const m={AU:'AUS',AUS:'AUS',NZ:'NZ',IE:'IRE',IRE:'IRE',UK:'GB',GB:'GB',FR:'FR',JP:'JPN',JPN:'JPN',US:'USA',USA:'USA',DE:'GER',GER:'GER'};const x=String(h.country||'').toUpperCase();return m[x]||x||'—';}
 function base(h){const v=typeof currentBase==='function'?currentBase(h.horse):null;return !v||v==='Researching'?'—':String(v).replace(/HORSE-SPECIFIC CURRENT/gi,'').replace(/TRAINER BASE FALLBACK/gi,'').trim();}
 function last(h){const runs=typeof publicRatedRuns==='function'?publicRatedRuns(h.horse):[],r=runs[0];return r?`${r.finish||'—'} - ${r.race||'—'}`:'—';}
 function state(x){if(x.qualified)return '<span class="oe-state qualified">QUALIFIED</span>';if(x.projected)return x.rank>=20?'<span class="oe-state bubble">BUBBLE</span>':'<span class="oe-state strong">PROJECTED IN</span>';if(x.rank)return '<span class="oe-state out">NEXT IN LINE</span>';return '<span class="oe-state neutral">NOMINATED</span>';}
 function position(x){return x.rank?`#${x.rank}`:'—';}
 window.orderProView=function(){const rs=allRows(),in24=rs.filter(x=>x.projected).length,bubble=rs.filter(x=>x.projected&&x.rank>=20).length,next=rs.filter(x=>x.rank>=25&&x.rank<=30).length;return `<div class="section-header oe-head"><div><div class="kicker">FLEMINGTON · 3200M · GROUP 1</div><h2>Order of Entry</h2></div></div><section class="oe-summary"><div><span>TOTAL NOMINATIONS</span><strong>${rs.length}</strong></div><div><span>PROJECTED IN</span><strong>${in24}</strong></div><div><span>BUBBLE</span><strong>${bubble}</strong></div><div><span>NEXT IN LINE</span><strong>${next}</strong></div><div><span>WEIGHTS RELEASE</span><strong>17 SEP</strong></div></section><div class="toolbar oe-toolbar"><div class="filters"><button class="filter active" data-oe="all">All Horses <span>${rs.length}</span></button><button class="filter" data-oe="in">Projected 24 <span>${in24}</span></button><button class="filter" data-oe="bubble">Bubble <span>${bubble}</span></button><button class="filter" data-oe="next">Next In Line <span>${next}</span></button><button class="filter" data-oe="international">International <span>${rs.filter(x=>x.h.trainingRegion==='International').length}</span></button></div><div class="oe-controls"><input id="oe-search" class="search" placeholder="Search horse or trainer…"><select id="oe-sort" class="oe-select"><option value="order">Sort: Projected Order</option><option value="az">Sort A–Z</option><option value="pfr">PFR high–low</option><option value="market">Market low–high</option></select><select id="oe-country" class="oe-select"><option value="all">All Countries</option></select></div></div><div id="oe-grid" class="oe-grid"></div>`;};
 window.paintOrderPro=function(filter='all',query='',sort='order',countryFilter='all'){const root=document.getElementById('oe-grid');if(!root)return;const q=query.trim().toLowerCase();let rs=allRows().filter(x=>(filter==='all'||filter==='in'&&x.projected||filter==='bubble'&&x.projected&&x.rank>=20||filter==='next'&&x.rank>=25&&x.rank<=30||filter==='international'&&x.h.trainingRegion==='International')&&(countryFilter==='all'||country(x.h)===countryFilter)&&(!q||`${x.h.horse} ${x.h.trainer} ${base(x.h)}`.toLowerCase().includes(q)));if(sort==='az')rs.sort((a,b)=>a.h.horse.localeCompare(b.h.horse));else if(sort==='pfr')rs.sort((a,b)=>Number(pfr(b.h.horse))-Number(pfr(a.h.horse)));else if(sort==='market')rs.sort((a,b)=>(marketRaw(a.h)??9999)-(marketRaw(b.h)??9999));root.innerHTML=rs.map(x=>`<button class="oe-card ${x.rank===24?'cut':''} ${x.rank===25?'firstout':''}" onclick="openHorse('${x.h.horse.replace(/'/g,"\\'")}')"><div class="oe-card-top"><b class="oe-rank">${position(x)}</b><span class="oe-silk">${typeof silkIcon==='function'?silkIcon(x.h.horse,'lg'):''}</span><div class="oe-id"><strong>${x.h.horse}</strong><span>${x.h.trainer}</span><span>${base(x.h)}</span></div><b class="oe-country">${country(x.h)}</b>${state(x)}</div><div class="oe-stats"><div><span>WT</span><strong>${wt(x.h.horse)}</strong></div><div><span>PFR</span><strong>${pfr(x.h.horse)}</strong></div><div><span>MARKET</span><strong>${market(x.h)}</strong></div><div><span>ORDER</span><strong>${x.rank||'—'}</strong></div></div><div class="oe-last"><span>Last run: <strong>${last(x.h)}</strong></span><b>›</b></div></button>`).join('');};
 function current(){return {filter:document.querySelector('[data-oe].active')?.dataset.oe||'all',q:document.getElementById('oe-search')?.value||'',sort:document.getElementById('oe-sort')?.value||'order',country:document.getElementById('oe-country')?.value||'all'};}
 function repaint(){const s=current();paintOrderPro(s.filter,s.q,s.sort,s.country);}
 document.addEventListener('click',e=>{const b=e.target.closest('[data-oe]');if(!b)return;document.querySelectorAll('[data-oe]').forEach(x=>x.classList.remove('active'));b.classList.add('active');repaint();});
 document.addEventListener('input',e=>{if(e.target?.id==='oe-search')repaint();});document.addEventListener('change',e=>{if(['oe-sort','oe-country'].includes(e.target?.id))repaint();});
 function show(){currentView='order';document.querySelectorAll('#nav button[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view==='order'));document.getElementById('page-title').textContent='Order of Entry';const root=document.getElementById('app-content'),go=()=>{root.innerHTML=orderProView();const sel=document.getElementById('oe-country');[...new Set(allRows().map(x=>country(x.h)))].sort().forEach(c=>sel.insertAdjacentHTML('beforeend',`<option value="${c}">${c}</option>`));paintOrderPro();};if(!projectedFieldData){root.innerHTML='<div class="placeholder">Loading…</div>';Promise.all([typeof loadProjectedField==='function'?loadProjectedField():Promise.resolve(),typeof loadExtras==='function'?loadExtras():Promise.resolve()]).then(go);}else go();}
 const legacyOpen=window.openView;window.openView=function(view){if(view==='order'){show();return;}return legacyOpen.apply(this,arguments);};document.addEventListener('click',e=>{const b=e.target.closest('#nav button[data-view="order"]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();show();},true);
})();