// PFR — approved professional 101-horse ratings workspace.
(function(){
 function rec(h){try{return typeof publicFormRating==='function'?publicFormRating(h):null}catch(e){return null}}
 function runs(h){try{return typeof publicRatedRuns==='function'?publicRatedRuns(h):[]}catch(e){return []}}
 function runRating(z){const vals=[z?.publicRating,z?.pfr,z?.rating];for(const v of vals){const n=Number(v);if(Number.isFinite(n)&&n>0)return n}if(typeof publicRunRating==='function'){try{const n=Number(publicRunRating(z));if(Number.isFinite(n)&&n>0)return n}catch(_){}}return null}
 function code(h){const m={AU:'AUS',AUS:'AUS',NZ:'NZ',IE:'IRE',IRE:'IRE',UK:'GB',GB:'GB',FR:'FR',JP:'JPN',JPN:'JPN',US:'USA',USA:'USA'};const x=String(h.country||'').toUpperCase();return m[x]||x||'—'}
 function trajectory(r){if(!r||r.trajectory==null)return {txt:'—',cls:'flat'};const v=Number(r.trajectory);return {txt:`${v>0?'+':''}${v.toFixed(1)}`,cls:v>1?'up':v<-1?'down':'flat'};}
 function last(h){const x=runs(h)[0];return x?`${x.finish||'—'} · ${x.race||x.track||'—'}`:'—'}
 function rows(){return (cupData?.horses||[]).map(h=>({h,r:rec(h.horse)}));}
 function leaders(){const a=rows().filter(x=>x.r);return {current:a.slice().sort((x,y)=>Number(y.r.current)-Number(x.r.current))[0],peak:a.slice().sort((x,y)=>Number(y.r.peak)-Number(x.r.peak))[0],improve:a.filter(x=>x.r.trajectory!=null).sort((x,y)=>Number(y.r.trajectory)-Number(x.r.trajectory))[0],stay:a.filter(x=>x.r.longStayPeak!=null).sort((x,y)=>Number(y.r.longStayPeak)-Number(x.r.longStayPeak))[0]};}
 window.pfrProView=function(){const L=leaders();return `<div class="pfr-head"><div><div class="kicker">FLEMINGTON · 3200M · GROUP 1</div><h2>PFR</h2><p>Performance Form Ratings across the complete 101-horse Melbourne Cup nomination universe.</p></div></div><section class="pfr-summary"><div><span>CURRENT LEADER</span><strong>${L.current?.h.horse||'—'}</strong><small>${L.current?Number(L.current.r.current).toFixed(1)+' PFR':'—'}</small></div><div><span>PEAK RATING</span><strong>${L.peak?.h.horse||'—'}</strong><small>${L.peak?Number(L.peak.r.peak).toFixed(1)+' peak':'—'}</small></div><div><span>FASTEST IMPROVER</span><strong>${L.improve?.h.horse||'—'}</strong><small>${L.improve?trajectory(L.improve.r).txt+' trajectory':'—'}</small></div><div><span>2800M+ LEADER</span><strong>${L.stay?.h.horse||'—'}</strong><small>${L.stay?Number(L.stay.r.longStayPeak).toFixed(1)+' staying PFR':'—'}</small></div></section><div class="pfr-toolbar"><input id="pfr-search" class="search" placeholder="Search horse or trainer…"><div class="filters"><button class="filter active" data-pfr="all">All Horses <span>101</span></button><button class="filter" data-pfr="top20">Top 20</button><button class="filter" data-pfr="improving">Improving</button><button class="filter" data-pfr="stayers">2800m+</button><button class="filter" data-pfr="international">International</button></div><select id="pfr-sort" class="pfr-select"><option value="current">Sort: Current PFR</option><option value="peak">Sort: Peak PFR</option><option value="trajectory">Sort: Trajectory</option><option value="az">Sort A–Z</option></select></div><div class="panel pfr-board"><div class="pfr-board-head"><div><h3>PFR Ratings Board · 101 Horses</h3><p>Current, peak and staying ratings with recent-form trajectory.</p></div><span id="pfr-count">101 horses</span></div><div class="table-wrap"><table class="data-table pfr-table"><thead><tr><th>#</th><th>Horse</th><th>Country</th><th>Trainer</th><th>Latest 3 PFR</th><th>Current</th><th>Peak</th><th>2800m+</th><th>Trajectory</th><th>Last Run</th></tr></thead><tbody id="pfr-body"></tbody></table></div></div>`;};
 window.paintPfrPro=function(filter='all',q='',sort='current'){let a=rows(),query=q.trim().toLowerCase();if(filter==='improving')a=a.filter(x=>Number(x.r?.trajectory)>0);else if(filter==='stayers')a=a.filter(x=>x.r?.longStayPeak!=null);else if(filter==='international')a=a.filter(x=>x.h.trainingRegion==='International');if(query)a=a.filter(x=>`${x.h.horse} ${x.h.trainer}`.toLowerCase().includes(query));const sorters={current:(x,y)=>(Number(y.r?.current)||-999)-(Number(x.r?.current)||-999),peak:(x,y)=>(Number(y.r?.peak)||-999)-(Number(x.r?.peak)||-999),trajectory:(x,y)=>(Number(y.r?.trajectory)||-999)-(Number(x.r?.trajectory)||-999),az:(x,y)=>x.h.horse.localeCompare(y.h.horse)};a.sort(sorters[sort]||sorters.current);if(filter==='top20')a=a.slice(0,20);const body=document.getElementById('pfr-body');if(!body)return;body.innerHTML=a.map((x,i)=>{const r=x.r,t=trajectory(r),rr=runs(x.h.horse).slice(0,3);return `<tr onclick="openHorse('${x.h.horse.replace(/'/g,"\\'")}')"><td>${i+1}</td><td class="horse">${typeof silkHorse==='function'?silkHorse(x.h.horse):horseLink(x.h.horse)}</td><td>${code(x.h)}</td><td>${x.h.trainer||'—'}</td><td><div class="pfr-last3">${rr.length?rr.map(z=>{const n=runRating(z);return `<b>${n!=null?n.toFixed(1):'—'}</b>`}).join(''):'—'}</div></td><td class="pfr-current">${r?Number(r.current).toFixed(1):'—'}</td><td class="pfr-peak">${r?Number(r.peak).toFixed(1):'—'}</td><td>${r?.longStayPeak!=null?Number(r.longStayPeak).toFixed(1):'—'}</td><td><span class="pfr-traj ${t.cls}">${t.txt}</span></td><td class="pfr-last">${last(x.h.horse)}</td></tr>`}).join('');document.getElementById('pfr-count').textContent=`Showing ${a.length} of 101 horses`;};
 function state(){return {f:document.querySelector('[data-pfr].active')?.dataset.pfr||'all',q:document.getElementById('pfr-search')?.value||'',s:document.getElementById('pfr-sort')?.value||'current'}}function repaint(){const x=state();paintPfrPro(x.f,x.q,x.s)}
 document.addEventListener('click',e=>{const b=e.target.closest('[data-pfr]');if(!b)return;document.querySelectorAll('[data-pfr]').forEach(x=>x.classList.remove('active'));b.classList.add('active');repaint()});document.addEventListener('input',e=>{if(e.target?.id==='pfr-search')repaint()});document.addEventListener('change',e=>{if(e.target?.id==='pfr-sort')repaint()});
 function show(){currentView='timeform';document.querySelectorAll('#nav button[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view==='timeform'));document.getElementById('page-title').textContent='PFR';const root=document.getElementById('app-content');const go=()=>{root.innerHTML=pfrProView();paintPfrPro()};if(!formIntelData){root.innerHTML='<div class="placeholder">Loading PFR…</div>';loadFormIntel().then(go)}else go()}
 const old=window.openView;window.openView=function(v){if(v==='timeform'){show();return}return old.apply(this,arguments)};document.addEventListener('click',e=>{if(!e.target.closest('#nav button[data-view="timeform"]'))return;e.preventDefault();e.stopImmediatePropagation();show()},true);
})();