// Ratings & Rankings — approved premium workspace standard.
(function(){
  let rrFilter='all',rrQuery='',rrSort='lens';
  function rows(){return typeof publicRankingRows==='function'?publicRankingRows():[];}
  function pfr(x){return Number(x.pfr?.current??x.r?.current);}
  function trend(x){const n=Number(x.r?.trajectory);if(!Number.isFinite(n))return '<span class="rr-trend flat">—</span>';const cls=n>=4?'up':n<=-4?'down':'flat';return `<span class="rr-trend ${cls}">${n>0?'+':''}${n.toFixed(1)}</span>`;}
  function market(x){try{const m=marketUniverse().find(z=>z.horse===x.h.horse);return m?.last?.odds?`$${Number(m.last.odds).toFixed(2)}`:'—';}catch(_){return '—';}}
  function filtered(){let a=rows().filter(x=>{if(rrFilter==='projected')return !!x.p;if(rrFilter==='international')return x.h.trainingRegion==='International';if(rrFilter==='stayers')return x.r?.longStayPeak!=null;if(rrFilter==='improving')return Number(x.r?.trajectory)>=4;return true;});const q=rrQuery.trim().toLowerCase();if(q)a=a.filter(x=>`${x.h.horse} ${x.h.trainer} ${x.h.country}`.toLowerCase().includes(q));return a.sort((a,b)=>{if(rrSort==='pfr')return (pfr(b)||-999)-(pfr(a)||-999);if(rrSort==='peak')return (Number(b.r?.peak)||-999)-(Number(a.r?.peak)||-999);if(rrSort==='stamina')return (Number(b.r?.longStayPeak)||-999)-(Number(a.r?.longStayPeak)||-999);if(rrSort==='projected')return (a.p?.rank??999)-(b.p?.rank??999);return (Number(b.lens?.score)||-999)-(Number(a.lens?.score)||-999);});}
  function view(){const all=rows(),rated=all.filter(x=>Number.isFinite(pfr(x))),stayers=all.filter(x=>x.r?.longStayPeak!=null),improving=all.filter(x=>Number(x.r?.trajectory)>=4),projected=all.filter(x=>x.p),intl=all.filter(x=>x.h.trainingRegion==='International');return `<div class="rr-head"><div class="kicker">FLEMINGTON · 3200M · GROUP 1</div><h2>Ratings & Rankings</h2><p>Complete 101-horse performance board combining PFR, peak performance, staying evidence, trajectory, handicap, market and Cup Lens.</p></div><section class="rr-summary"><div><span>NOMINEES</span><strong>${all.length}</strong><small>Complete Cup universe</small></div><div><span>PFR RATED</span><strong>${rated.length}</strong><small>Known rating available</small></div><div><span>2800M+ RATED</span><strong>${stayers.length}</strong><small>Long-staying evidence</small></div><div><span>IMPROVING</span><strong>${improving.length}</strong><small>Positive PFR trajectory</small></div><div><span>PROJECTED</span><strong>${projected.length}/24</strong><small>Current field projection</small></div><div><span>INTERNATIONAL</span><strong>${intl.length}</strong><small>Overseas-trained nominees</small></div></section><div class="rr-toolbar"><input id="rr-search" class="search" type="search" placeholder="Search horse or trainer…"><div class="filters"><button class="filter active" data-rr="all">All Horses <span>${all.length}</span></button><button class="filter" data-rr="projected">Projected 24</button><button class="filter" data-rr="stayers">2800m+</button><button class="filter" data-rr="improving">Improving</button><button class="filter" data-rr="international">International <span>${intl.length}</span></button></div><select id="rr-sort" class="rr-select"><option value="lens">Sort: Cup Lens</option><option value="pfr">Sort: Current PFR</option><option value="peak">Sort: Peak PFR</option><option value="stamina">Sort: 2800m+</option><option value="projected">Sort: Projected Field</option></select></div><div class="panel rr-board"><div class="rr-board-head"><div><h3>101-Horse Rating Board</h3><p>Click a horse for its full profile and form history.</p></div><span id="rr-count"></span></div><div class="table-wrap"><table class="data-table rr-table"><thead><tr><th>Rank</th><th>Horse</th><th>Country</th><th>Trainer</th><th>Current PFR</th><th>Peak</th><th>R&S</th><th>2400m+</th><th>2800m+</th><th>Trajectory</th><th>Wt</th><th>Projected</th><th>Market</th><th>Cup Lens</th></tr></thead><tbody id="rr-body"></tbody></table></div></div>`;}
  function paint(){const a=filtered(),body=document.getElementById('rr-body');if(!body)return;document.getElementById('rr-count').textContent=`Showing ${a.length} of ${rows().length}`;body.innerHTML=a.map((x,i)=>{const ras=typeof publicRasPeak==='function'?publicRasPeak(x.h.horse):null;return `<tr onclick="openHorse('${x.h.horse.replace(/'/g,"\\'")}')"><td class="rr-rank">${i+1}</td><td class="horse">${typeof silkHorse==='function'?silkHorse(x.h.horse):horseLink(x.h.horse)}</td><td>${x.h.country||'—'}</td><td>${x.h.trainer||'—'}</td><td class="rr-score">${Number.isFinite(pfr(x))?pfr(x).toFixed(1):'—'}</td><td>${Number.isFinite(Number(x.r?.peak))?Number(x.r.peak).toFixed(1):'—'}</td><td>${ras??'—'}</td><td>${Number.isFinite(Number(x.r?.stayingPeak))?Number(x.r.stayingPeak).toFixed(1):'—'}</td><td>${Number.isFinite(Number(x.r?.longStayPeak))?Number(x.r.longStayPeak).toFixed(1):'—'}</td><td>${trend(x)}</td><td>${x.w?Number(x.w.predictedKg).toFixed(1)+'kg':'—'}</td><td class="rr-proj">${x.p?'#'+x.p.rank:'—'}</td><td>${market(x)}</td><td class="rr-score">${x.lens?Number(x.lens.score).toFixed(1):'—'}</td></tr>`;}).join('');}
  function bind(){document.querySelectorAll('[data-rr]').forEach(b=>b.onclick=()=>{rrFilter=b.dataset.rr;document.querySelectorAll('[data-rr]').forEach(x=>x.classList.toggle('active',x===b));paint();});const s=document.getElementById('rr-search');if(s)s.oninput=()=>{rrQuery=s.value;paint();};const sort=document.getElementById('rr-sort');if(sort)sort.onchange=()=>{rrSort=sort.value;paint();};paint();}
  function show(){currentView='ratings';selectedHorse=null;document.getElementById('page-title').textContent='Ratings & Rankings';document.querySelectorAll('#nav button[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view==='ratings'));const root=document.getElementById('app-content');const need=[];if(!formIntelData&&typeof loadFormIntel==='function')need.push(loadFormIntel());if(!weightPredictions&&typeof loadExtras==='function')need.push(loadExtras());if(!projectedFieldData&&typeof loadProjectedField==='function')need.push(loadProjectedField());if(need.length){root.innerHTML='<div class="placeholder">Loading ratings…</div>';Promise.allSettled(need).then(show);return;}root.innerHTML=view();bind();}
  const baseRender=window.render;window.render=function(v='dashboard'){if(v==='ratings'){show();return;}return baseRender(v);};
  const baseOpen=window.openView;window.openView=function(v){if(v==='ratings'){show();return;}return baseOpen(v);};
  document.addEventListener('click',e=>{const b=e.target.closest('#nav button[data-view="ratings"]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();show();},true);
})();