// Weights & Handicap — approved premium racing workspace standard.
(function(){
  if(typeof weightsView!=='function')return;
  function rows(){const hs=cupData?.horses||[];return hs.map(h=>{const p=typeof weightRec==='function'?weightRec(h.horse):null;const o=typeof orderOfficialWeight==='function'?orderOfficialWeight(h.horse):null;return {h,p,official:Number.isFinite(o)?o:null};}).sort((a,b)=>(b.official??Number(b.p?.predictedKg)??-1)-(a.official??Number(a.p?.predictedKg)??-1)||a.h.horse.localeCompare(b.h.horse));}
  function pfr(name){const r=typeof publicFormRating==='function'?publicFormRating(name):null;return Number.isFinite(Number(r?.current))?Number(r.current).toFixed(1):'—';}
  function market(h){const m=typeof marketUniverse==='function'?marketUniverse().find(x=>x.horse===h.horse):null;const o=Number(m?.last?.odds??h.marketOdds);return Number.isFinite(o)&&o>1?`$${o.toFixed(2)}`:'—';}
  function range(p){return p&&Number.isFinite(Number(p.rangeLow))&&Number.isFinite(Number(p.rangeHigh))?`${Number(p.rangeLow).toFixed(1)}–${Number(p.rangeHigh).toFixed(1)}`:'—';}
  function status(h){return GOLDEN_TICKETS.has(h.horse)?'<span class="nom-status qualified">QUALIFIED</span>':'<span class="nom-status">NOMINATED</span>';}
  weightsView=function(){const rs=rows(),officialCount=rs.filter(x=>x.official!=null).length,modelled=rs.filter(x=>Number.isFinite(Number(x.p?.predictedKg))).length;const official=officialCount>0;return `<div class="section-header wh-head"><div><div class="kicker">FLEMINGTON · 3200M · GROUP 1</div><h2>Weights & Handicap</h2></div></div><section class="wh-summary"><div><span>NOMINATIONS</span><strong>${rs.length}</strong></div><div><span>${official?'OFFICIAL WEIGHTS':'PROJECTED WEIGHTS'}</span><strong>${official?officialCount:modelled}</strong></div><div><span>TOP WEIGHT</span><strong>${rs.length?(rs[0].official??Number(rs[0].p?.predictedKg)).toFixed(1):'—'}<small> kg</small></strong></div><div><span>HANDICAPS</span><strong>${official?'OFFICIAL':'17 SEP'}</strong></div></section><div class="toolbar wh-toolbar"><div class="filters"><button class="filter active" data-wh-filter="all">All Horses <span>${rs.length}</span></button><button class="filter" data-wh-filter="ticket">Qualified <span>${rs.filter(x=>GOLDEN_TICKETS.has(x.h.horse)).length}</span></button></div><input id="wh-search" class="search" type="search" placeholder="Search horse or trainer…"></div><div class="panel wh-panel"><div class="table-wrap"><table class="data-table wh-table"><thead><tr><th>#</th><th>Horse</th><th>Country</th><th>Trainer</th><th>${official?'Official Wt':'Projected Wt'}</th><th>Range</th><th>PFR</th><th>Market</th><th>Tier</th><th>Confidence</th><th>Status</th></tr></thead><tbody id="wh-body"></tbody></table></div></div>`;};
  window.paintWeights=function(filter='all',query=''){const body=document.getElementById('wh-body');if(!body)return;const q=query.trim().toLowerCase();const rs=rows().filter(x=>(filter==='all'||GOLDEN_TICKETS.has(x.h.horse))&&(!q||`${x.h.horse} ${x.h.trainer} ${x.h.country}`.toLowerCase().includes(q)));body.innerHTML=rs.map((x,i)=>{const wt=x.official??Number(x.p?.predictedKg);return `<tr><td>${i+1}</td><td class="horse">${typeof silkHorse==='function'?silkHorse(x.h.horse):horseLink(x.h.horse)}</td><td>${x.h.country||'—'}</td><td>${x.h.trainer||'—'}</td><td class="wh-weight"><strong>${Number.isFinite(wt)?wt.toFixed(1):'—'}</strong></td><td>${range(x.p)}</td><td class="wh-pfr">${pfr(x.h.horse)}</td><td>${market(x.h)}</td><td>${x.p?.tier||'—'}</td><td>${x.p?.confidence||'—'}</td><td>${status(x.h)}</td></tr>`}).join('');};
  document.addEventListener('click',e=>{const b=e.target.closest('[data-wh-filter]');if(!b)return;document.querySelectorAll('[data-wh-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');paintWeights(b.dataset.whFilter,document.getElementById('wh-search')?.value||'');});
  document.addEventListener('input',e=>{if(e.target?.id!=='wh-search')return;paintWeights(document.querySelector('[data-wh-filter].active')?.dataset.whFilter||'all',e.target.value);});
  const priorRender=render;render=function(view='dashboard'){if(view==='weights'){document.getElementById('page-title').textContent='Weights & Handicap';const root=document.getElementById('app-content');if(!weightPredictions){root.innerHTML='<div class="placeholder">Loading…</div>';loadExtras().then(()=>render(view));return;}root.innerHTML=weightsView();paintWeights();return;}priorRender(view);};
})();