// Weights & Handicap — official-v-prediction comparison workspace.
(function(){
  if(typeof weightsView!=='function')return;
  const norm=s=>String(s||'').toLowerCase().replace(/[’']/g,'').replace(/[^a-z0-9]/g,'');
  function officialFor(name){const k=norm(name);const r=(officialWeights?.weights||[]).find(x=>norm(x.horse)===k);return Number.isFinite(Number(r?.weightKg))?Number(r.weightKg):null;}
  function rows(){return (cupData?.horses||[]).map(h=>{const p=typeof weightRec==='function'?weightRec(h.horse):null;const official=officialFor(h.horse);const predicted=Number.isFinite(Number(p?.predictedKg))?Number(p.predictedKg):null;return {h,p,official,predicted,delta:official!=null&&predicted!=null?official-predicted:null};}).sort((a,b)=>(b.official??-1)-(a.official??-1)||a.h.horse.localeCompare(b.h.horse));}
  function pfr(name){const r=typeof publicFormRating==='function'?publicFormRating(name):null;return Number.isFinite(Number(r?.current))?Number(r.current).toFixed(1):'—';}
  function market(h){const m=typeof marketUniverse==='function'?marketUniverse().find(x=>x.horse===h.horse):null;const o=Number(m?.last?.odds??h.marketOdds);return Number.isFinite(o)&&o>1?`$${o.toFixed(2)}`:'—';}
  function status(h){return GOLDEN_TICKETS.has(h.horse)?'<span class="nom-status qualified">QUALIFIED</span>':'<span class="nom-status">NOMINATED</span>';}
  function deltaCell(d){if(d==null)return '—';return `<strong>${d>0?'+':''}${d.toFixed(1)}</strong>`;}
  function stats(rs){const paired=rs.filter(x=>x.delta!=null),abs=paired.map(x=>Math.abs(x.delta));return {paired:paired.length,mae:abs.length?abs.reduce((a,b)=>a+b,0)/abs.length:null,exact:paired.filter(x=>Math.abs(x.delta)<0.001).length,within05:paired.filter(x=>Math.abs(x.delta)<=0.5).length,within10:paired.filter(x=>Math.abs(x.delta)<=1).length};}
  weightsView=function(){const rs=rows(),s=stats(rs),officialCount=rs.filter(x=>x.official!=null).length;return `<div class="section-header wh-head"><div><div class="kicker">OFFICIAL HANDICAPS · 17 SEPTEMBER 2026</div><h2>Weights & Handicap</h2><div class="section-copy">Racing Australia official handicap beside our frozen pre-release estimate. Variance = Official − Predicted.</div></div></div><section class="wh-summary"><div><span>OFFICIAL WEIGHTS</span><strong>${officialCount}</strong></div><div><span>PAIRED PREDICTIONS</span><strong>${s.paired}</strong></div><div><span>MEAN ABS ERROR</span><strong>${s.mae==null?'—':s.mae.toFixed(2)}<small> kg</small></strong></div><div><span>WITHIN 1.0 KG</span><strong>${s.within10}<small> / ${s.paired}</small></strong></div><div><span>EXACT</span><strong>${s.exact}</strong></div></section><div class="toolbar wh-toolbar"><div class="filters"><button class="filter active" data-wh-filter="all">All Horses <span>${rs.length}</span></button><button class="filter" data-wh-filter="close">Within 0.5kg <span>${s.within05}</span></button><button class="filter" data-wh-filter="shock">Miss ≥2kg <span>${rs.filter(x=>x.delta!=null&&Math.abs(x.delta)>=2).length}</span></button><button class="filter" data-wh-filter="ticket">Qualified <span>${rs.filter(x=>GOLDEN_TICKETS.has(x.h.horse)).length}</span></button></div><input id="wh-search" class="search" type="search" placeholder="Search horse or trainer…"></div><div class="panel wh-panel"><div class="table-wrap"><table class="data-table wh-table"><thead><tr><th>#</th><th>Horse</th><th>Country</th><th>Trainer</th><th>Official</th><th>Our Prediction</th><th>Variance</th><th>PFR</th><th>Market</th><th>Confidence</th><th>Status</th></tr></thead><tbody id="wh-body"></tbody></table></div></div>`;};
  window.paintWeights=function(filter='all',query=''){const body=document.getElementById('wh-body');if(!body)return;const q=query.trim().toLowerCase();const rs=rows().filter(x=>{const f=filter==='all'||(filter==='ticket'&&GOLDEN_TICKETS.has(x.h.horse))||(filter==='close'&&x.delta!=null&&Math.abs(x.delta)<=0.5)||(filter==='shock'&&x.delta!=null&&Math.abs(x.delta)>=2);return f&&(!q||`${x.h.horse} ${x.h.trainer} ${x.h.country}`.toLowerCase().includes(q));});body.innerHTML=rs.map((x,i)=>`<tr><td>${i+1}</td><td class="horse">${typeof silkHorse==='function'?silkHorse(x.h.horse):horseLink(x.h.horse)}</td><td>${x.h.country||'—'}</td><td>${x.h.trainer||'—'}</td><td class="wh-weight"><strong>${x.official==null?'—':x.official.toFixed(1)}</strong></td><td>${x.predicted==null?'—':x.predicted.toFixed(1)}</td><td>${deltaCell(x.delta)}</td><td class="wh-pfr">${pfr(x.h.horse)}</td><td>${market(x.h)}</td><td>${x.p?.confidence||'—'}</td><td>${status(x.h)}</td></tr>`).join('');};
  document.addEventListener('click',e=>{const b=e.target.closest('[data-wh-filter]');if(!b)return;document.querySelectorAll('[data-wh-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');paintWeights(b.dataset.whFilter,document.getElementById('wh-search')?.value||'');});
  document.addEventListener('input',e=>{if(e.target?.id!=='wh-search')return;paintWeights(document.querySelector('[data-wh-filter].active')?.dataset.whFilter||'all',e.target.value);});
  const priorRender=render;render=function(view='dashboard'){if(view==='weights'){document.getElementById('page-title').textContent='Weights & Handicap';const root=document.getElementById('app-content');if(!weightPredictions||!officialWeights){root.innerHTML='<div class="placeholder">Loading official weights…</div>';loadExtras().then(()=>render(view));return;}root.innerHTML=weightsView();paintWeights();return;}priorRender(view);};
})();